/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DebugProtoTest_constants.h"

namespace thrift { namespace test { namespace debug {

const DebugProtoTestConstants g_DebugProtoTest_constants;

DebugProtoTestConstants::DebugProtoTestConstants() {
  COMPACT_TEST.a_byte = 127;
  COMPACT_TEST.__isset.a_byte = true;
  COMPACT_TEST.a_i16 = 32000;
  COMPACT_TEST.__isset.a_i16 = true;
  COMPACT_TEST.a_i32 = 1000000000;
  COMPACT_TEST.__isset.a_i32 = true;
  COMPACT_TEST.a_i64 = 1099511627775LL;
  COMPACT_TEST.__isset.a_i64 = true;
  COMPACT_TEST.a_double = 5.6789;
  COMPACT_TEST.__isset.a_double = true;
  COMPACT_TEST.a_string = "my string";
  COMPACT_TEST.__isset.a_string = true;
  COMPACT_TEST.true_field = true;
  COMPACT_TEST.__isset.true_field = true;
  COMPACT_TEST.false_field = false;
  COMPACT_TEST.__isset.false_field = true;
  Empty tmp627;

  COMPACT_TEST.empty_struct_field = tmp627;
  COMPACT_TEST.__isset.empty_struct_field = true;
  std::vector<int8_t>  tmp628;
  tmp628.push_back(-127);
  tmp628.push_back(-1);
  tmp628.push_back(0);
  tmp628.push_back(1);
  tmp628.push_back(127);

  COMPACT_TEST.byte_list = tmp628;
  COMPACT_TEST.__isset.byte_list = true;
  std::vector<int16_t>  tmp629;
  tmp629.push_back(-1);
  tmp629.push_back(0);
  tmp629.push_back(1);
  tmp629.push_back(32767);

  COMPACT_TEST.i16_list = tmp629;
  COMPACT_TEST.__isset.i16_list = true;
  std::vector<int32_t>  tmp630;
  tmp630.push_back(-1);
  tmp630.push_back(0);
  tmp630.push_back(255);
  tmp630.push_back(65535);
  tmp630.push_back(16777215);
  tmp630.push_back(2147483647);

  COMPACT_TEST.i32_list = tmp630;
  COMPACT_TEST.__isset.i32_list = true;
  std::vector<int64_t>  tmp631;
  tmp631.push_back(-1LL);
  tmp631.push_back(0LL);
  tmp631.push_back(255LL);
  tmp631.push_back(65535LL);
  tmp631.push_back(16777215LL);
  tmp631.push_back(4294967295LL);
  tmp631.push_back(1099511627775LL);
  tmp631.push_back(281474976710655LL);
  tmp631.push_back(72057594037927935LL);
  tmp631.push_back(9223372036854775807LL);

  COMPACT_TEST.i64_list = tmp631;
  COMPACT_TEST.__isset.i64_list = true;
  std::set<double>  tmp632;
  tmp632.insert(0.1);
  tmp632.insert(0.2);
  tmp632.insert(0.3);

  COMPACT_TEST.double_set = tmp632;
  COMPACT_TEST.__isset.double_set = true;
  std::set<std::string>  tmp633;
  tmp633.insert("first");
  tmp633.insert("second");
  tmp633.insert("third");

  COMPACT_TEST.string_set = tmp633;
  COMPACT_TEST.__isset.string_set = true;
  std::set<bool>  tmp634;
  tmp634.insert(true);
  tmp634.insert(false);

  COMPACT_TEST.boolean_set = tmp634;
  COMPACT_TEST.__isset.boolean_set = true;
  std::set<Empty>  tmp635;
  Empty tmp636;

  tmp635.insert(tmp636);

  COMPACT_TEST.struct_set = tmp635;
  COMPACT_TEST.__isset.struct_set = true;
  std::map<int8_t, int8_t>  tmp637;
  tmp637.insert(std::make_pair(1, 2));

  COMPACT_TEST.byte_byte_map = tmp637;
  COMPACT_TEST.__isset.byte_byte_map = true;
  std::map<int16_t, int8_t>  tmp638;
  tmp638.insert(std::make_pair(1, 1));
  tmp638.insert(std::make_pair(-1, 1));
  tmp638.insert(std::make_pair(32767, 1));

  COMPACT_TEST.i16_byte_map = tmp638;
  COMPACT_TEST.__isset.i16_byte_map = true;
  std::map<int32_t, int8_t>  tmp639;
  tmp639.insert(std::make_pair(1, 1));
  tmp639.insert(std::make_pair(-1, 1));
  tmp639.insert(std::make_pair(2147483647, 1));

  COMPACT_TEST.i32_byte_map = tmp639;
  COMPACT_TEST.__isset.i32_byte_map = true;
  std::map<int64_t, int8_t>  tmp640;
  tmp640.insert(std::make_pair(0LL, 1));
  tmp640.insert(std::make_pair(1LL, 1));
  tmp640.insert(std::make_pair(-1LL, 1));
  tmp640.insert(std::make_pair(9223372036854775807LL, 1));

  COMPACT_TEST.i64_byte_map = tmp640;
  COMPACT_TEST.__isset.i64_byte_map = true;
  std::map<double, int8_t>  tmp641;
  tmp641.insert(std::make_pair(-1.1, 1));
  tmp641.insert(std::make_pair(1.1, 1));

  COMPACT_TEST.double_byte_map = tmp641;
  COMPACT_TEST.__isset.double_byte_map = true;
  std::map<std::string, int8_t>  tmp642;
  tmp642.insert(std::make_pair("first", 1));
  tmp642.insert(std::make_pair("second", 2));
  tmp642.insert(std::make_pair("third", 3));
  tmp642.insert(std::make_pair("", 0));

  COMPACT_TEST.string_byte_map = tmp642;
  COMPACT_TEST.__isset.string_byte_map = true;
  std::map<bool, int8_t>  tmp643;
  tmp643.insert(std::make_pair(true, 1));
  tmp643.insert(std::make_pair(false, 0));

  COMPACT_TEST.boolean_byte_map = tmp643;
  COMPACT_TEST.__isset.boolean_byte_map = true;
  std::map<int8_t, int16_t>  tmp644;
  tmp644.insert(std::make_pair(1, 1));
  tmp644.insert(std::make_pair(2, -1));
  tmp644.insert(std::make_pair(3, 32767));

  COMPACT_TEST.byte_i16_map = tmp644;
  COMPACT_TEST.__isset.byte_i16_map = true;
  std::map<int8_t, int32_t>  tmp645;
  tmp645.insert(std::make_pair(1, 1));
  tmp645.insert(std::make_pair(2, -1));
  tmp645.insert(std::make_pair(3, 2147483647));

  COMPACT_TEST.byte_i32_map = tmp645;
  COMPACT_TEST.__isset.byte_i32_map = true;
  std::map<int8_t, int64_t>  tmp646;
  tmp646.insert(std::make_pair(1, 1LL));
  tmp646.insert(std::make_pair(2, -1LL));
  tmp646.insert(std::make_pair(3, 9223372036854775807LL));

  COMPACT_TEST.byte_i64_map = tmp646;
  COMPACT_TEST.__isset.byte_i64_map = true;
  std::map<int8_t, double>  tmp647;
  tmp647.insert(std::make_pair(1, 0.1));
  tmp647.insert(std::make_pair(2, -0.1));
  tmp647.insert(std::make_pair(3, 1e+06));

  COMPACT_TEST.byte_double_map = tmp647;
  COMPACT_TEST.__isset.byte_double_map = true;
  std::map<int8_t, std::string>  tmp648;
  tmp648.insert(std::make_pair(1, ""));
  tmp648.insert(std::make_pair(2, "blah"));
  tmp648.insert(std::make_pair(3, "loooooooooooooong string"));

  COMPACT_TEST.byte_string_map = tmp648;
  COMPACT_TEST.__isset.byte_string_map = true;
  std::map<int8_t, bool>  tmp649;
  tmp649.insert(std::make_pair(1, true));
  tmp649.insert(std::make_pair(2, false));

  COMPACT_TEST.byte_boolean_map = tmp649;
  COMPACT_TEST.__isset.byte_boolean_map = true;
  std::map<std::vector<int8_t> , int8_t>  tmp650;
  std::vector<int8_t>  tmp651;
  tmp651.push_back(1);
  tmp651.push_back(2);
  tmp651.push_back(3);

  tmp650.insert(std::make_pair(tmp651, 1));
  std::vector<int8_t>  tmp652;
  tmp652.push_back(0);
  tmp652.push_back(1);

  tmp650.insert(std::make_pair(tmp652, 2));
  std::vector<int8_t>  tmp653;

  tmp650.insert(std::make_pair(tmp653, 0));

  COMPACT_TEST.list_byte_map = tmp650;
  COMPACT_TEST.__isset.list_byte_map = true;
  std::map<std::set<int8_t> , int8_t>  tmp654;
  std::set<int8_t>  tmp655;
  tmp655.insert(1);
  tmp655.insert(2);
  tmp655.insert(3);

  tmp654.insert(std::make_pair(tmp655, 1));
  std::set<int8_t>  tmp656;
  tmp656.insert(0);
  tmp656.insert(1);

  tmp654.insert(std::make_pair(tmp656, 2));
  std::set<int8_t>  tmp657;

  tmp654.insert(std::make_pair(tmp657, 0));

  COMPACT_TEST.set_byte_map = tmp654;
  COMPACT_TEST.__isset.set_byte_map = true;
  std::map<std::map<int8_t, int8_t> , int8_t>  tmp658;
  std::map<int8_t, int8_t>  tmp659;
  tmp659.insert(std::make_pair(1, 1));

  tmp658.insert(std::make_pair(tmp659, 1));
  std::map<int8_t, int8_t>  tmp660;
  tmp660.insert(std::make_pair(2, 2));

  tmp658.insert(std::make_pair(tmp660, 2));
  std::map<int8_t, int8_t>  tmp661;

  tmp658.insert(std::make_pair(tmp661, 0));

  COMPACT_TEST.map_byte_map = tmp658;
  COMPACT_TEST.__isset.map_byte_map = true;
  std::map<int8_t, std::map<int8_t, int8_t> >  tmp662;
  std::map<int8_t, int8_t>  tmp663;

  tmp662.insert(std::make_pair(0, tmp663));
  std::map<int8_t, int8_t>  tmp664;
  tmp664.insert(std::make_pair(1, 1));

  tmp662.insert(std::make_pair(1, tmp664));
  std::map<int8_t, int8_t>  tmp665;
  tmp665.insert(std::make_pair(1, 1));
  tmp665.insert(std::make_pair(2, 2));

  tmp662.insert(std::make_pair(2, tmp665));

  COMPACT_TEST.byte_map_map = tmp662;
  COMPACT_TEST.__isset.byte_map_map = true;
  std::map<int8_t, std::set<int8_t> >  tmp666;
  std::set<int8_t>  tmp667;

  tmp666.insert(std::make_pair(0, tmp667));
  std::set<int8_t>  tmp668;
  tmp668.insert(1);

  tmp666.insert(std::make_pair(1, tmp668));
  std::set<int8_t>  tmp669;
  tmp669.insert(1);
  tmp669.insert(2);

  tmp666.insert(std::make_pair(2, tmp669));

  COMPACT_TEST.byte_set_map = tmp666;
  COMPACT_TEST.__isset.byte_set_map = true;
  std::map<int8_t, std::vector<int8_t> >  tmp670;
  std::vector<int8_t>  tmp671;

  tmp670.insert(std::make_pair(0, tmp671));
  std::vector<int8_t>  tmp672;
  tmp672.push_back(1);

  tmp670.insert(std::make_pair(1, tmp672));
  std::vector<int8_t>  tmp673;
  tmp673.push_back(1);
  tmp673.push_back(2);

  tmp670.insert(std::make_pair(2, tmp673));

  COMPACT_TEST.byte_list_map = tmp670;
  COMPACT_TEST.__isset.byte_list_map = true;
  std::vector<double>  tmp674;
  tmp674.push_back(0.1);
  tmp674.push_back(0.2);
  tmp674.push_back(0.3);

  COMPACT_TEST.double_list = tmp674;
  COMPACT_TEST.__isset.double_list = true;
  std::vector<std::string>  tmp675;
  tmp675.push_back("first");
  tmp675.push_back("second");
  tmp675.push_back("third");

  COMPACT_TEST.string_list = tmp675;
  COMPACT_TEST.__isset.string_list = true;
  std::vector<bool>  tmp676;
  tmp676.push_back(true);
  tmp676.push_back(true);
  tmp676.push_back(true);
  tmp676.push_back(false);
  tmp676.push_back(false);
  tmp676.push_back(false);

  COMPACT_TEST.boolean_list = tmp676;
  COMPACT_TEST.__isset.boolean_list = true;
  std::vector<Empty>  tmp677;
  Empty tmp678;

  tmp677.push_back(tmp678);
  Empty tmp679;

  tmp677.push_back(tmp679);

  COMPACT_TEST.struct_list = tmp677;
  COMPACT_TEST.__isset.struct_list = true;
  std::set<int8_t>  tmp680;
  tmp680.insert(-127);
  tmp680.insert(-1);
  tmp680.insert(0);
  tmp680.insert(1);
  tmp680.insert(127);

  COMPACT_TEST.byte_set = tmp680;
  COMPACT_TEST.__isset.byte_set = true;
  std::set<int16_t>  tmp681;
  tmp681.insert(-1);
  tmp681.insert(0);
  tmp681.insert(1);
  tmp681.insert(32767);

  COMPACT_TEST.i16_set = tmp681;
  COMPACT_TEST.__isset.i16_set = true;
  std::set<int32_t>  tmp682;
  tmp682.insert(1);
  tmp682.insert(2);
  tmp682.insert(3);

  COMPACT_TEST.i32_set = tmp682;
  COMPACT_TEST.__isset.i32_set = true;
  std::set<int64_t>  tmp683;
  tmp683.insert(-1LL);
  tmp683.insert(0LL);
  tmp683.insert(255LL);
  tmp683.insert(65535LL);
  tmp683.insert(16777215LL);
  tmp683.insert(4294967295LL);
  tmp683.insert(1099511627775LL);
  tmp683.insert(281474976710655LL);
  tmp683.insert(72057594037927935LL);
  tmp683.insert(9223372036854775807LL);

  COMPACT_TEST.i64_set = tmp683;
  COMPACT_TEST.__isset.i64_set = true;

  MYCONST = 2;

  MY_SOME_ENUM = (SomeEnum::type)1;

  MY_SOME_ENUM_1 = (SomeEnum::type)1;

  MY_ENUM_MAP.insert(std::make_pair((SomeEnum::type)1, (SomeEnum::type)2));

  StructWithSomeEnum tmp684;
  tmp684.blah = (SomeEnum::type)2;
  tmp684.__isset.blah = true;

  EXTRA_CRAZY_MAP.insert(std::make_pair((SomeEnum::type)1, tmp684));

}

}}} // namespace

